version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: nme/nme-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: nme/nme-registry
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: nme/nme-gateway
    restart: always
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      NOTIFICATION_SERVICE_PASSWORD: $NOTIFICATION_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: nme/nme-auth-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: nme/nme-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: nme/nme-account-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: nme/nme-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      NOTIFICATION_SERVICE_PASSWORD: $NOTIFICATION_SERVICE_PASSWORD
    image: nme/nme-notification-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-mongodb:
    image: nme/nme-mongodb
    restart: always
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  transaction-service:
      environment:
        CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
        ACCOUNT_SERVICE_PASSWORD: $TRANSACTION_SERVICE_PASSWORD
        MONGODB_PASSWORD: $MONGODB_PASSWORD
      image: nme/nme-account-service
      restart: always
      logging:
        options:
          max-size: "10m"
          max-file: "10"

  transaction-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: nme/nme-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  customer-service:
      environment:
        CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
        ACCOUNT_SERVICE_PASSWORD: $CUSTOMER_SERVICE_PASSWORD
        MONGODB_PASSWORD: $MONGODB_PASSWORD
      image: nme/nme-customer-service
      restart: always
      logging:
        options:
          max-size: "10m"
          max-file: "10"

  customer-mongodb:
    environment:
      INIT_DUMP: customer-service-dump.js
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: nme/nme-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"